name: matah
recipe: laravel

config:
  via: nginx
  composer_version: 2-latest
  webroot: public
  database: mysql:8.0
  cache: redis
  xdebug: true
  php: "8.0"

proxy:
  mailhog:
    - mail.matah.lndo.site

services:
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom: []

  database:
    portforward: 3307
    run_as_root:
      - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS testing; GRANT ALL PRIVILEGES ON testing.* TO 'laravel'@'%';"

tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit
