<?php

namespace App\Nova;

use App\Helpers\RoleList;
use App\Models\CompanyGroup as CompanyGroupModel;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class CompanyGroup extends Resource
{
    public static $model = CompanyGroupModel::class;

    public static $title = 'name';

    public static $group = 'Company';

    public static $search = [
        ''
    ];

    public function fields(Request $request): array
    {
        return [
            ID::make()->sortable(),

            Text::make('Name')
                ->rules('required')
                ->sortable(),

            BelongsTo::make('Company')
                ->sortable(),
        ];
    }

    public static function indexQuery(NovaRequest $request, $query): \Illuminate\Database\Eloquent\Builder
    {
        if ($request->user()->isRoleMatch(RoleList::WAREHOUSE_ADMIN)) {
            return $query
                ->where('company_id', $request->user()->company->company_id);
        }

        return parent::indexQuery($request, $query); // TODO: Change the autogenerated stub
    }

    public function cards(Request $request): array
    {
        return [];
    }

    public function filters(Request $request): array
    {
        return [];
    }

    public function lenses(Request $request): array
    {
        return [];
    }

    public function actions(Request $request): array
    {
        return [];
    }
}
